#!/bin/bash

title="Kawaii faces:"
widthpercent=10

typeset -A menu
menu=(
    [¯\_(ツ)_/¯]="~/sh_kawaiifaces 1"
    [( ͡° ͜ʖ ͡°)]="~/sh_kawaiifaces 2"
    [ಠ_ಠ]="~/sh_kawaiifaces 3"
    [◕‿◕]="~/sh_kawaiifaces 4"
    [(╯°□°）╯︵ ┻━┻]="~/sh_kawaiifaces 5"
    [Cancel]=""
)
menu_nrows=${#menu[@]}
