#!/bin/bash

title="Kawaii faces:"
widthpercent=13

typeset -A menu
menu=(
    [1 - ¯\_(ツ)_/¯]="~/sh_kawaiifaces 1"
    [2 - ( ͡° ͜ʖ ͡°)]="~/sh_kawaiifaces 2"
    [3 - ಠ_ಠ]="~/sh_kawaiifaces 3"
    [4 - ◕‿◕]="~/sh_kawaiifaces 4"
    [5 - (╯°□°）╯︵ ┻━┻]="~/sh_kawaiifaces 5"
)
menu_nrows=${#menu[@]}
