#!/bin/bash
case "$1" in
    1)  face='¯\_(ツ)_/¯' 
        ;;
    2)  face='( ͡° ͜ʖ ͡°)' 
        ;;
    *)  face='error' 
        ;;
esac

echo -n $face | xclip 
echo -n $face | xclip -selection clipboard
